version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/headlines-vue
    branches:
      only:
        - master
        - develop
      ignore:
        - gh-pages

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test

      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"

      - deploy:
          name: Deploy
          command: sh ./deploy.sh
